### PR TITLE
Readme proposal

### PR DESCRIPTION
**Pull request by da-ekchajzer**
I propose these few changes to the README to simplify the content a little and expand the scope of the project to cloud (not for data collection, but as a modelization use case).

Do not hesitate if you wish to make any changes. 

@maethor what are your thoughts about it ? (I cannot set you as a reviewer, since you haven't accepted the invite to the repo yet)

### CODE REVIEW

**Comment by maethor** [comment]
Hm. I am not sure I am seeing all the changes. I only see a new line in introduction, which I am totally OK with.

I don't agree that we should expand the scope to "cloud" (maybe define what cloud you are talking about? IAAS? PAAS?). I think the main goal should be focus to collect and report precise (and real) data on physical machines. A lot of projects are already trying to modelize and guess power consumption for the cloud, and will benefit from this work on hardware.

I think we should limit the scope to hardware.

I mean, that's what I think. But I will be very happy to discuss this with you and the rest of the team in a future meeting.

**Comment by da-ekchajzer** [comment]
Sorry, my bad, I just pushed the right version.

I think we are saying the same thing. Energizta won't collect data on the cloud, but the outputs could be used to model the consumption on cloud environment. I just mention the use case as a possible outcome of the project.

**Comment by maethor** [comment]
I am ok with everything you rewrote.

I don't know AWS catalog but if your example is a virtual machine I still believe it should be out of scope (the FAQ explain why). On the cloud you do not have access to CPU model, so modeling the power consumption will be a lot harder (and imprecise).

**Comment by da-ekchajzer** [comment]
For AWS EC2 we can retrieve the underlying architecture from AWS documentation, see for instance : https://github.com/Boavizta/boaviztapi/tree/dev/boaviztapi/data/devices/cloud/aws

**Comment by da-ekchajzer** [comment]
@maethor are you ok to merge this version ?

**Pull request merged**
